swagger:
  enable: true
  client-id: sdf
  client-secret: sdfsd
  access-token-uri: http://localhost:18888/oauth/token
  base-package: com.sigma.examples
  base-path: /api/**
  api-names:
    -
    - samples
#  version: v2

spring:
  application:
    name: samples

aliyun:
  sms:
    access-key-id: NRcyUO
    secret: wZ920z2Ss2zlsafZ
    sign-name: 注册验证
  oss:
    access-key-id: XXXX
    secret: OOOOOOOO
    end-point: oss-cn-hangzhou.aliyuncs.com
    buckets:
     - public
     - private

sigmapay:
  wxpay:
    app-id: wx
    merchant-id: 136381
    app-key: Lm0qodcpPTN