swagger:
  enable: true
  client-id:
  client-secret:
  access-token-uri: http://localhost:18889/auth/oauth/token
  base-package: com.sigma.examples
  base-path: /api/**
  api-names:
    - samples
  version: v2

spring:
  application:
    name: samples

aliyun:
  sms:
    access-key-id: NRcyUO
    secret: wZ920z2Ss2zlsafZ
    sign-name: 注册验证