spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sigma
    username: root
    password: root
server:
  port: 9999

master: true

sigma:
  scheduler:
    master: true
  dist:
    zookeeper:
      url: 172.18.21.144:2181